### ISSUE TITLE
Not recompiling on saving changes to Styles.fs

### ISSUE THREAD

**Issue by simax** [elmish/sample-rn-counter#1]
I followed the instructions in the readme and everything works as expected. If I save changes to the app.fs file then fable re-compiles. However, it doesn't recompile if I make changes to Styles.fs. It's as though it's only watching app.fs. Any idea why?

**Comment by et1975** [comment]
Can confirm, fable doesn't notice the change in Styles.fs unless App.fs changes. @alfonsogarciacaro, @forki any idea?

**Comment by forki** [comment]
Remove all inline keywords and try again.

Eugene Tolmachev <notifications@github.com> schrieb am Fr., 1. Juni 2018,
18:09:

**Comment by simax** [comment]
I removed all `inline` as suggested. I also needed to `npm i buffer --save` after getting
`Unable to resolve module buffer from Fable.ReactHelpers.js` error. 

But now when I make and save changes to `Styles.js` the fable compiler re-compiles. Yeah!

Thanks for your help guys and for your very prompt response!
